image: mcr.microsoft.com/devcontainers/base:ubuntu

tasks:
  - name: Start Apache NiFi
    command: |
      docker-compose up -d
      sleep 20

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
